/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views.patient;

import controllers.LoginController;
import controllers.PatientController;
import java.awt.CardLayout;
import javax.swing.JPanel;
import models.user.Patient;
import views.LoginPage;

/**
 *
 * @author kushp
 */
public class PatientHomePage extends javax.swing.JPanel {

    /**
     * Creates new form PatientView
     */
    JPanel bottomPanel;
    PatientController patientController;
    public PatientHomePage(JPanel bottomPanel, PatientController patientController) {
        this.bottomPanel = bottomPanel;
        this.patientController = patientController;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMakeAppointment = new javax.swing.JButton();
        btnViewAppointments = new javax.swing.JButton();
        btnViewRecord = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnHomePage = new javax.swing.JButton();

        btnMakeAppointment.setText("Make Appointment");
        btnMakeAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMakeAppointmentActionPerformed(evt);
            }
        });

        btnViewAppointments.setText("View Appointments");
        btnViewAppointments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAppointmentsActionPerformed(evt);
            }
        });

        btnViewRecord.setText("View My Record");
        btnViewRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewRecordActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Patient Home Page");

        btnHomePage.setText("Log Out");
        btnHomePage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomePageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                        .addComponent(btnHomePage))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnViewRecord, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                        .addComponent(btnViewAppointments, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                        .addComponent(btnMakeAppointment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnHomePage))
                .addGap(35, 35, 35)
                .addComponent(btnMakeAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnViewAppointments, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnViewRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(157, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMakeAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMakeAppointmentActionPerformed
        bottomPanel.add(new PatientAppointmentPage(bottomPanel, patientController));
        CardLayout cl = (CardLayout) bottomPanel.getLayout();
        cl.next(bottomPanel);
    }//GEN-LAST:event_btnMakeAppointmentActionPerformed

    private void btnViewAppointmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAppointmentsActionPerformed
        bottomPanel.add(new ListAppointmentPage(bottomPanel, patientController));
        CardLayout cl = (CardLayout) bottomPanel.getLayout();
        cl.next(bottomPanel);
    }//GEN-LAST:event_btnViewAppointmentsActionPerformed

    private void btnViewRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewRecordActionPerformed
        bottomPanel.add(new ViewMyDetailsPage(bottomPanel, patientController.getPatient()));
        CardLayout cl = (CardLayout) bottomPanel.getLayout();
        cl.next(bottomPanel);
    }//GEN-LAST:event_btnViewRecordActionPerformed

    private void btnHomePageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomePageActionPerformed
        bottomPanel.removeAll();
        bottomPanel.add(new LoginPage(bottomPanel, new LoginController()));
        CardLayout cl = (CardLayout) bottomPanel.getLayout();
        cl.next(bottomPanel);
    }//GEN-LAST:event_btnHomePageActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHomePage;
    private javax.swing.JButton btnMakeAppointment;
    private javax.swing.JButton btnViewAppointments;
    private javax.swing.JButton btnViewRecord;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
